name: Release

on:
  push:
    paths:
      - package.json
      - .github/workflows/gh-release.yml
      - .github/workflows/release-tag.sh

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: bun i && bun run build

      - name: Create release with tag
        run: sh .github/workflows/release-tag.sh
        env:
          title: 🚀 Release
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

