# .github/workflows/release.yml
name: Create Release on version change

on:
  push:
    paths:
      - package.json
      - .github/workflows/gh-release.yml
      - .github/workflows/release-tag.sh

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create release from tag
        uses: marco-souza/tag-release@1.2.0
        with:
          title: 🚀 Release
          version-file: package.json
          token: ${{ secrets.GITHUB_TOKEN }}
